"""add_moneybox_table

Revision ID: 1b7eef7cdb83
Revises: 
Create Date: 2024-02-17 19:42:46.380716

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b7eef7cdb83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneybox',
    sa.Column('name', sa.String(), nullable=False, comment='The name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneybox'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneybox')
    # ### end Alembic commands ###
