"""add_moneybox_table

Revision ID: 2c5bac118e9e
Revises: 
Create Date: 2024-02-05 23:21:28.606239

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c5bac118e9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneybox',
    sa.Column('name', sa.String(), nullable=False, comment='The unique name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneybox')
    # ### end Alembic commands ###
