"""add_note_column_to_tables

Revision ID: 653f527d540f
Revises: 4c2c3a87248c
Create Date: 2024-08-04 01:49:49.427158

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utc

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '653f527d540f'
down_revision: Union[str, None] = '4c2c3a87248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moneyboxes', sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'))
    op.add_column('transactions', sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'note')
    op.drop_column('moneyboxes', 'note')
    # ### end Alembic commands ###
