"""add_note_column_to_tables

Revision ID: 653f527d540f
Revises: 4c2c3a87248c
Create Date: 2024-08-04 01:49:49.427158

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utc

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '653f527d540f'
down_revision: Union[str, None] = '4c2c3a87248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moneyboxes', sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'))
    op.add_column('transactions', sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'))
    op.alter_column('transactions', 'counterparty_moneybox_id',
               existing_type=sa.INTEGER(),
               comment='Transaction is a transfer between moneybox_id and counterparty_moneybox_id, if set.',
               existing_comment='This is the ID of the counterparty moneybox at the time of the transaction.',
               existing_nullable=True)
    op.drop_column('transactions', 'counterparty_moneybox_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('counterparty_moneybox_name', sa.VARCHAR(), autoincrement=False, nullable=True, comment='This is the name of the counterperty moneybox at the time of the transaction.'))
    op.alter_column('transactions', 'counterparty_moneybox_id',
               existing_type=sa.INTEGER(),
               comment='This is the ID of the counterparty moneybox at the time of the transaction.',
               existing_comment='Transaction is a transfer between moneybox_id and counterparty_moneybox_id, if set.',
               existing_nullable=True)
    op.drop_column('transactions', 'note')
    op.drop_column('moneyboxes', 'note')
    # ### end Alembic commands ###
