"""set_index_to_moneybox_name

Revision ID: 6951dd272288
Revises: a1e370c69d18
Create Date: 2024-02-12 21:33:14.108366

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6951dd272288'
down_revision: Union[str, None] = 'a1e370c69d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_moneybox_name', 'moneybox', [sa.text('LOWER(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moneybox_name', table_name='moneybox')
    # ### end Alembic commands ###
