"""remove_automated_saving_trigger_day_from_app_settings_table

Revision ID: 83ce3642f332
Revises: a3cb260cb89f
Create Date: 2024-08-16 18:18:43.844404

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83ce3642f332'
down_revision: Union[str, None] = 'a3cb260cb89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'automated_saving_trigger_day')

    # Drop the Enum type 'triggerday' manually
    op.execute('DROP TYPE IF EXISTS triggerday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Define and create the enum type 'triggerday' if it does not already exist
    triggerday_enum = postgresql.ENUM('FIRST_OF_MONTH', 'MIDDLE_OF_MONTH', 'LAST_OF_MONTH', name='triggerday')
    triggerday_enum.create(op.get_bind(), checkfirst=True)

    # Add the column
    op.add_column('app_settings', sa.Column(
        'automated_saving_trigger_day',
        triggerday_enum,
        server_default=sa.text("'FIRST_OF_MONTH'::triggerday"),
        autoincrement=False,
        nullable=False,
        comment='The automated saving trigger day.'
    ))
