"""add_moneybox_table

Revision ID: a1e370c69d18
Revises: 
Create Date: 2024-02-11 01:37:50.226959

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1e370c69d18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneybox',
    sa.Column('name', sa.String(), nullable=False, comment='The unique name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneybox')),
    sa.UniqueConstraint('name', name=op.f('uq_moneybox_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneybox')
    # ### end Alembic commands ###
