"""add_overflow_moneybox_automated_savings_mode_to_app_sattings

Revision ID: a539d5488387
Revises: fac2992c1fdf
Create Date: 2024-08-18 07:21:18.519896

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a539d5488387'
down_revision: Union[str, None] = 'fac2992c1fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Define and create the enum type 'triggerday' if it does not already exist
    # Enum type creation
    overflowmoneyboxautomatedsavingsmodetype = sa.Enum(
        'COLLECT',
        'ADD_TO_AUTOMATED_SAVINGS_AMOUNT',
        'FILL_UP_LIMITED_MONEYBOXES',
        name='overflowmoneyboxautomatedsavingsmodetype'
    )
    overflowmoneyboxautomatedsavingsmodetype.create(op.get_bind())

    # Add column with the new Enum type
    op.add_column('app_settings', sa.Column(
        'overflow_moneybox_automated_savings_mode',
        overflowmoneyboxautomatedsavingsmodetype,
        server_default='COLLECT',
        nullable=False,
        comment='The mode for the overflow moneybox, which will have an influence on the automated savings process.'
    ))
    ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'overflow_moneybox_automated_savings_mode')

    # Drop the Enum type 'overflowmoneyboxautomatedsavingsmodetype' manually
    op.execute('DROP TYPE IF EXISTS overflowmoneyboxautomatedsavingsmodetype')
    # ### end Alembic commands ###
