"""add_moneybox_table

Revision ID: bb354b32277a
Revises: 
Create Date: 2024-02-27 14:24:43.007562

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb354b32277a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneyboxes',
    sa.Column('name', sa.String(), nullable=False, comment='The name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='The created utc datetime.'),
    sa.Column('modified_at', sa.DateTime(), nullable=True, comment='The modified utc datetime.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneyboxes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moneyboxes')
    # ### end Alembic commands ###
