"""add_description_column_to_moneyboxes_table

Revision ID: d426eb2a54d7
Revises: e15f08736162
Create Date: 2024-12-08 14:51:29.251988

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd426eb2a54d7'
down_revision: Union[str, None] = 'e15f08736162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moneyboxes', sa.Column('description', sa.String(), server_default='', nullable=False, comment='The current priority of the moneybox. There is only one moneybox with a priority of Null (will be the marker for the overflow moneybox. And only disables moneyboxes cant have e NULL value as priority.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moneyboxes', 'description')
    # ### end Alembic commands ###
