"""app_v2_init_migration

Revision ID: f67dffcb50b4
Revises: 
Create Date: 2024-08-05 09:52:00.849141

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.utils import get_vanilla_datetime

# revision identifiers, used by Alembic.
revision: str = 'f67dffcb50b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneyboxes',
    sa.Column('name', sa.String(), nullable=False, comment='The name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('savings_amount', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='The current savings amount of the moneybox.'),
    sa.Column('savings_target', sa.Integer(), nullable=True, comment='The current savings target. Is relevant for the automated distributed saving progress.'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='The current priority of the moneybox. There is only one moneybox with a priority of Null (will be the marker for the overflow moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='The created utc datetime.'),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True, comment='The modified utc datetime.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneyboxes')),
    sa.UniqueConstraint('priority', name=op.f('uq_moneyboxes_priority')),
    sa.CheckConstraint('priority >= 0', name='ck_moneyboxes_priority_nonnegative')
    )
    op.create_table('transactions',
    sa.Column('description', sa.String(), nullable=False, comment='The description of the transaction action.'),
    sa.Column('transaction_type', sa.Enum('DIRECT', 'DISTRIBUTION', name='transactiontype'), nullable=False, comment='The type of the transaction. Possible values: direct or distribution.'),
    sa.Column('transaction_trigger', sa.Enum('MANUALLY', 'AUTOMATICALLY', name='transactiontrigger'), nullable=False, comment='The transaction trigger type, possible values: manually, automatically. Says, if balance was deposit or withdrawn manually or automatically.'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='The current amount of the transaction. Can be negative, negative = withdraw, positive = deposit.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The balance of the moneybox at the time of the transaction.'),
    sa.Column('counterparty_moneybox_id', sa.Integer(), nullable=True, comment='Transaction is a transfer between moneybox_id and counterparty_moneybox_id, if set.'),
    sa.Column('moneybox_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='The created utc datetime.'),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True, comment='The modified utc datetime.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'),
    sa.ForeignKeyConstraint(['counterparty_moneybox_id'], ['moneyboxes.id'], name=op.f('fk_transactions_counterparty_moneybox_id_moneyboxes')),
    sa.ForeignKeyConstraint(['moneybox_id'], ['moneyboxes.id'], name=op.f('fk_transactions_moneybox_id_moneyboxes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.execute(
        """
        CREATE UNIQUE INDEX idx_unique_moneyboxes_name_active
        ON moneyboxes(name)
        WHERE is_active = 1;
        """
    )

    # Insert initial moneybox data with priority = NULL
    new_moneybox = {
        "name": str(uuid.uuid4()),
        "created_at": get_vanilla_datetime().isoformat(sep=" "),
        "balance": 0,
        "savings_amount": 0,
        "savings_target": None,
        "is_active": True,
        "priority": 0,
    }

    connection = op.get_bind()
    connection.execute(
        sa.text("""
                    INSERT INTO moneyboxes (name, created_at, balance, savings_amount, savings_target, is_active, priority)
                    VALUES (:name, :created_at, :balance, :savings_amount, :savings_target, :is_active, :priority)
                """).params(**new_moneybox)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_unique_moneyboxes_name_active')
    op.drop_table('transactions')
    op.drop_table('moneyboxes')
    # ### end Alembic commands ###