# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  issues: read
  pull-requests: read
  checks: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gnupg2 wget nano python3-pip python3-venv
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        sudo apt update
        sudo apt install -y postgresql-client-16
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath
        export PATH="$HOME/.local/bin:$PATH"
        pipx install poetry
        poetry install --with dev

    - name: Run tests
      run: poetry run pytest --cov-fail-under=90
