"""app_v2_init_migration

Revision ID: 98226b1185e7
Revises: 
Create Date: 2024-08-05 04:04:11.579399

"""
import datetime
import uuid
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '98226b1185e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moneyboxes',
    sa.Column('name', sa.String(), nullable=False, comment='The name of a moneybox.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The current balance of the moneybox.'),
    sa.Column('savings_amount', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='The current savings amount of the moneybox.'),
    sa.Column('savings_target', sa.Integer(), nullable=True, comment='The current savings target. Is relevant for the automated distributed saving progress.'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='The current priority of the moneybox. There is only one moneybox with a priority of Null (will be the marker for the overflow moneybox.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False, comment='The created utc datetime.'),
    sa.Column('modified_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True, comment='The modified utc datetime.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_moneyboxes')),
    sa.UniqueConstraint('priority', name=op.f('uq_moneyboxes_priority'))
    )
    op.create_table('transactions',
    sa.Column('description', sa.String(), nullable=False, comment='The description of the transaction action.'),
    sa.Column('transaction_type', sa.Enum('DIRECT', 'DISTRIBUTION', name='transactiontype'), nullable=False, comment='The type of the transaction. Possible values: direct or distribution.'),
    sa.Column('transaction_trigger', sa.Enum('MANUALLY', 'AUTOMATICALLY', name='transactiontrigger'), nullable=False, comment='The transaction trigger type, possible values: manually, automatically. Says, if balance was deposit or withdrawn manually or automatically.'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='The current amount of the transaction. Can be negative, negative = withdraw, positive = deposit.'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='The balance of the moneybox at the time of the transaction.'),
    sa.Column('counterparty_moneybox_id', sa.Integer(), nullable=True, comment='Transaction is a transfer between moneybox_id and counterparty_moneybox_id, if set.'),
    sa.Column('moneybox_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='The primary ID of the row.'),
    sa.Column('created_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False, comment='The created utc datetime.'),
    sa.Column('modified_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True, comment='The modified utc datetime.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag to mark instance as deleted.'),
    sa.Column('note', sa.String(), server_default='', nullable=True, comment='The note of this record'),
    sa.ForeignKeyConstraint(['counterparty_moneybox_id'], ['moneyboxes.id'], name=op.f('fk_transactions_counterparty_moneybox_id_moneyboxes')),
    sa.ForeignKeyConstraint(['moneybox_id'], ['moneyboxes.id'], name=op.f('fk_transactions_moneybox_id_moneyboxes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )

    op.execute(
        'CREATE INDEX idx_moneyboxes_name_active '
        'ON moneyboxes(name) '
        'WHERE is_active = true'
    )

    # Insert initial moneybox data with priority = NULL
    new_moneybox = {
        "name": str(uuid.uuid4()),
        "created_at": datetime.datetime.now(tz=datetime.timezone.utc),
        "balance": 0,
        "savings_amount": 0,
        "savings_target": None,
        "is_active": True,
        "priority": None
    }

    connection = op.get_bind()
    connection.execute(
        sa.text("""
                   INSERT INTO moneyboxes (name, created_at, balance, savings_amount, savings_target, is_active, priority)
                   VALUES (:name, :created_at, :balance, :savings_amount, :savings_target, :is_active, :priority)
               """).params(**new_moneybox)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX idx_moneyboxes_name_active')

    op.drop_table('transactions')
    op.drop_table('moneyboxes')
    # ### end Alembic commands ###
